version: '3.3'
services:
  api:
    image: pokemon-api
    container_name: pokemon-api
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/api
    environment:
      - MONGO_URL=mongodb://mongo/pokemon
    links:
      - mongo
  mongo:
    image: mongo:4.2
    container_name: pokemon-db
    restart: always
    ports:
      - 27017:27017
